spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flwl?characterEncoding=utf8&useSSL=false
  sleuth:
    enabled: false
  zipkin:
    locator:
      discovery:
        enabled: true
zipkin:
  collector:
    rabbitmq:
      addresses: localhost:5672
      username: flwl
      password: Rabbit2019
      queue: 
  storage:
    type: mysql
