spring:
  datasource:
    url: jdbc:mysql://192.168.0.135:3306/cloud?characterEncoding=utf8&useSSL=false
#    schema: classpath:mysql.sql
  # sleuth:
  #   enabled: false
  # zipkin:
  #   locator:
  #     discovery:
  #       enabled: true

zipkin:
  collector:
    rabbitmq:
      addresses: 120.79.244.56:5672
      username: guest
      password: guest
      queue: zipkin
  storage:
    type: mysql