server:
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true

management:
  security:
    enabled: false

spring:
  aop:
    proxy-target-class: true
    auto: true
  rabbitmq:
    host: 192.168.0.158
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 192.168.0.158
    password: scjjcredis
    port: 6379
    timeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 100
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: root
        login-password: sccdmysql
  mail:
    host: smtp.qq.com
    username: abelethan@vip.qq.com
    password: wttscxmovqcidida
    port: 25
    protocol: smtp
    test-connection: false
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 25
          starttls:
            enable: true
            required: true
  boot:
    admin:
      username: chongqing
      password: brigade
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: false
  httpclient:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true

ribbon:
  eager-load:
    enabled: true
    clients: brigade-auth,brigade-privider-manager
  Httpclient:
    enabled: true
  OkHttp:
    enabled: false
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

info:
  软件著作权: brigade重庆文旅分布式微服务平台
  作者: AbelEthan
  邮件: abelethan@126.com, abelethan@sina.cn, abelethan@aliyun.com, abelethan@vip.qq.com

ignore:
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120
  aliyun:
    key:
      accessKeyId: 'your aliyun accessKeyId'
      accessKeySecret: 'your aliyun accessKeySecret'
    rocketMq:
      namesrvAddr: http://192.168.0.135:9876
    sms:
      signName: 快乐学习网
      regionId: cn-beijing
      endpoint:
      endpointName: cn-beijing
      product: 'your sms product'
      domain: dysmsapi.aliyuncs.com
  zk:
    zkAddressList: 192.168.0.158:2181