spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://120.79.244.56:3306/cloud?characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://192.168.1.8:3306/cloud?characterEncoding=utf8&useSSL=false