spring:
  http:
    encoding:
      charset: UTF-8
  datasource:
    # url: jdbc:mysql://120.79.244.56:3306/cloud?characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://192.168.0.158:3306/cloud?characterEncoding=utf8&useSSL=false
brigade:
  ignore:
    urls:
    - /**/*.css
    - /auth/**
    - /admin/user/mobile/**
    - /refresh/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /*/v2/api-docs
    - /webjars/**
    - /actuator/**
    - /image/**
    - /sdk/config/upload