spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    uac-route:
      path: /uac/**
      sensitiveHeaders:
#      strip-prefix: false
      serviceId: brigade-provider-uac
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    mdc-route:
      path: /mdc/**
      sensitiveHeaders:
      serviceId: brigade-provider-mdc
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    opc-route:
      path: /opc/**
      sensitiveHeaders:
      serviceId: brigade-provider-opc
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
#    mall-route:
#      path: /mall/**
#      sensitiveHeaders:
#      serviceId: brigade-web-mall
#      ribbon:
#        eager-load:
#          enabled: true
#        MaxAutoRetries: 1
#        MaxAutoRetriesNextServer: 2
#        OkToRetryOnAllOperations: false
#        ConnectTimeout: 10000
#        ReadTimeout: 10000
    tpc-route:
      path: /tpc/**
      sensitiveHeaders:
      serviceId: brigade-provider-tpc
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    auth-route:
      path: /sac/**
      sensitiveHeaders:
      serviceId: brigade-service-auth
      ribbon:
        eager-loal:
          enabled: true
      MaxAutoRetries: 1
      MaxAutoRetriesNextServer: 2
      OkToRetryOnAllOperations: false
      ConnectTimeout: 10000
      ReadTimeout: 10000
  add-proxy-headers: true
  add-host-header: true

security:
  oauth2:
    client:
      clientId: brigade-client-gateway
      clientSecret: brigadeClientSecret
      access-token-uri: http://localhost:7979/sac/oauth/token
      user-authorization-uri: http://localhost:7979/sac/oauth/authorize
    resource:
      user-info-uri: http://localhost:7979/sac/user
      prefer-token-info: false
      jwt:
        key-uri: http://localhost:8090/sac/oauth/token_key

proxy:
  auth:
    routes:
      auth-route: oauth2
      uac-route: oauth2
      mdc-route: oauth2

brigade:
  enableSqlLogInterceptor: false
# swagger butler配置
swagger.butler:
  api-docs-path: v2/api-docs
  swagger-version: 1.0
  auto-generate-from-zuul-routes: true
# 指定要生成的范围
  generate-routes: mdc-route,opc-route,tpc-route,uac-route,auth-route
# 忽略某些路由生成
#  ignore-routes: